ERROR:root:OOPS
Traceback (most recent call last):
  File "rtmbot.py", line 161, in main_loop
    bot.start()
  File "rtmbot.py", line 34, in start
    for reply in self.slack_client.rtm_read():
  File "/Users/cristhiandick/anaconda/lib/python3.4/site-packages/slackclient/_client.py", line 39, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/Users/cristhiandick/anaconda/lib/python3.4/site-packages/slackclient/_server.py", line 110, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/Users/cristhiandick/anaconda/lib/python3.4/site-packages/websocket/_core.py", line 351, in recv
    opcode, data = self.recv_data()
  File "/Users/cristhiandick/anaconda/lib/python3.4/site-packages/websocket/_core.py", line 368, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/Users/cristhiandick/anaconda/lib/python3.4/site-packages/websocket/_core.py", line 381, in recv_data_frame
    frame = self.recv_frame()
  File "/Users/cristhiandick/anaconda/lib/python3.4/site-packages/websocket/_core.py", line 413, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/Users/cristhiandick/anaconda/lib/python3.4/site-packages/websocket/_abnf.py", line 312, in recv_frame
    self.recv_header()
  File "/Users/cristhiandick/anaconda/lib/python3.4/site-packages/websocket/_abnf.py", line 261, in recv_header
    header = self.recv_strict(2)
  File "/Users/cristhiandick/anaconda/lib/python3.4/site-packages/websocket/_abnf.py", line 346, in recv_strict
    bytes = self.recv(min(16384, shortage))
  File "/Users/cristhiandick/anaconda/lib/python3.4/site-packages/websocket/_core.py", line 482, in _recv
    return recv(self.sock, bufsize)
  File "/Users/cristhiandick/anaconda/lib/python3.4/site-packages/websocket/_socket.py", line 77, in recv
    bytes = sock.recv(bufsize)
  File "/Users/cristhiandick/anaconda/lib/python3.4/ssl.py", line 736, in recv
    return self.read(buflen)
  File "/Users/cristhiandick/anaconda/lib/python3.4/ssl.py", line 625, in read
    v = self._sslobj.read(len or 1024)
ConnectionResetError: [Errno 54] Connection reset by peer
quote vrx
ERROR:root:OOPS
Traceback (most recent call last):
  File "rtmbot.py", line 161, in main_loop
    bot.start()
  File "rtmbot.py", line 35, in start
    self.input(reply)
  File "rtmbot.py", line 52, in input
    plugin.do(function_name, data)
  File "rtmbot.py", line 109, in do
    eval("self.module."+function_name)(data)
  File "/Users/cristhiandick/node/stock-quote-slackbot/plugins/stockbot/stockbot.py", line 24, in process_message
    message = data["text"].lower()
KeyError: 'text'
quote
